version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
    depends_on:
      - db
    networks:
      - app-network
    restart: always

  db:
    image: cockroachdb/cockroach:v21.2.8
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach_data:/cockroach/cockroach-data
    networks:
      - app-network
    restart: always

  nginx:
    image: nginx:1.18
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /path/to/ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  cockroach_data:
